### ISSUE TITLE
Unauthorized : The request must be signed

### ISSUE THREAD

**Issue by companje** [3DHubs/sdk-php#2]
When I try to run `app/example.php` with my credentials (`consumer_key` and `consumer_secret`) filled in I get the following error: `Client error response .... Unauthorized : The request must be signed`.
Any ideas?

```
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] http://test.3dhubs.com/api/v1/model [status code] 401 [reason phrase] Unauthorized : The request must be signed' in ................./3dhubs-sdk-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:67
Stack trace:
#0 ............3dhubs-sdk-php/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(31): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 .............3dhubs-sdk-php/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(105): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 .............3dhubs-sdk-php/vendor/guzzlehttp/guzzle/src/Event/RequestEvents.php(75): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 ............3dhubs-sdk-php/vendor/guzzlehttp/guzz in......../3dhubs-sdk-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 67
```

**Comment by MarkDurbin104** [comment]
change line 8 to:
`define('API_HOST', 'https://www.3dhubs.com');`

**Comment by companje** [comment]
nice! that works.
